### ISSUE TITLE
Remove 'code' tag from PostReadingTime component

### ISSUE THREAD

**Issue by rsneh** [rsneh/liqras#14]
PostReadingTime component is responsible for showing the time it takes to read this post.
This component should ignore "code" blocks in the post and calculate only words to read.

**Comment by Siddharth1010** [comment]
Hey @rsneh , Which file is this function in?

**Comment by rsneh** [comment]
> Hey @rsneh , Which file is this function in?

Hi @Siddharth1010 👋🏼
This function is in utils/helpers.js

**Comment by Siddharth1010** [comment]
@rsneh Will this be alright?
![image](https://user-images.githubusercontent.com/59433969/104165546-89f22800-541f-11eb-9db6-1e7b2aac6015.png)

**Comment by Siddharth1010** [comment]
If it is not let me know :)
I'll change it before I create a PR

**Comment by rsneh** [comment]
I confused you with this solution. I think a better approach for this issue will be changing the PostReadingTime component.
I'll rename this issue and add some description as well.
Sorry about that.

**Comment by Siddharth1010** [comment]
> I confused you with this solution. I think a better approach for this issue will be changing the PostReadingTime component.
> I'll rename this issue and add some description as well.
> Sorry about that.

So basically I can just paste what I have done in the PostReadingTime file right?

**Comment by rsneh** [comment]
> > I confused you with this solution. I think a better approach for this issue will be changing the PostReadingTime component.
> > I'll rename this issue and add some description as well.
> > Sorry about that.
> 
> So basically I can just paste what I have done in the PostReadingTime file right?

Not exactly.
You can see in PostReadingTime.js line 5, there is already a reduce function to push all words.
You need to add a condition to check if this block is "code" to ignore it and continue with the loop.

**Comment by Siddharth1010** [comment]
I think I get it now. Could you tell me what the variable "block" is exactly?

**Comment by rsneh** [comment]
> I think I get it now. Could you tell me what the variable "block" is exactly?

Sure. But I think it will be best for you to install the repo on your local and explore it yourself.
Anyway, you can see the "initialBlocks" variable with a single block in context/PostContext.js line 5.

**Comment by Siddharth1010** [comment]
Ah thanks for that. Will this work?
![image](https://user-images.githubusercontent.com/59433969/104169339-6af69480-5425-11eb-81ed-213a3469a49a.png)

**Comment by rsneh** [comment]
> Ah thanks for that. Will this work?
> ![image](https://user-images.githubusercontent.com/59433969/104169339-6af69480-5425-11eb-81ed-213a3469a49a.png)

Not exactly.
Reduce has to return a value, so you need to change it to something like:
```javascript
const words = blocks.reduce((words, block) => {
  if (block.tag !== "code") block.html.trim().split(' ').forEach(word => word && words.push(word))
  return words
}, [])
```

**Comment by Siddharth1010** [comment]
I'm sorry about that. I should've looked up the syntax. But I'll keep it in mind next time. Thank you :)
Shall I create a PR?

**Comment by rsneh** [comment]
> I'm sorry about that. I should've looked up the syntax. But I'll keep it in mind next time. Thank you :)
> Shall I create a PR?

Yes.
Thanks
